name: Fetch and save random Pokemon

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC daily
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  fetch-and-save-pokemon:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
    
    - name: Run tests
      run: pytest -v

    - name: Create directories
      run: |
        mkdir -p logs
        mkdir -p pokemon_data
    
    - name: Fetch random Pokemon and save response
      run: |
        python -c "
        import json
        from datetime import datetime
        from pokemon_api import fetch_random_pokemon
        
        # Fetch Pokemon data
        pokemon_data = fetch_random_pokemon()
        
        # Create data entry
        data_entry = {
            'timestamp': datetime.now().isoformat(),
            'pokemon_data': pokemon_data
        }

        # Save to response.json for polling
        with open('pokemon_data/response.json', 'w') as f:
            json.dump(data_entry, f, indent=2)
        
         # Save to log file with today's date
        log_file = f'logs/pokemon_{datetime.now().strftime(\"%Y-%m-%d\")}.json'
        with open(log_file, 'w') as f:
            json.dump(data_entry, f, indent=2)
        "

    - name: Commit and push latest Pokemon
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pokemon_data/response.json
        git commit -m "Update Pokemon of the day" || exit 0
        git push
    
    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: pokemon-logs
        path: logs/*.json
        retention-days: 30