name: Send random Pokemon to trmnl

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-to-trmnl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
    
    - name: Run tests
      run: pytest -v

    - name: Create logs directory
      run: mkdir -p logs
    
    - name: Fetch random Pokemon and send to webhook
      env:
        TRMNL_WEBHOOK_URL: ${{ secrets.TRMNL_WEBHOOK_URL }}
      run: |
        python -c "
        import json
        from datetime import datetime
        from pokemon_api import fetch_random_pokemon
        from post_to_webhook import send_pokemon_to_trmnl
        
        # Fetch Pokemon data
        pokemon_data = fetch_random_pokemon()
        
        # Create log entry
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'pokemon_data': pokemon_data
        }
        
         # Save to log file with today's date
        log_file = f'logs/pokemon_{datetime.now().strftime(\"%Y-%m-%d\")}.json'
        with open(log_file, 'w') as f:
            json.dump(log_entry, f, indent=2)
            
        # Send to webhook
        send_pokemon_to_trmnl(pokemon_data)
        "
    
    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: pokemon-logs
        path: logs/*.json
        retention-days: 30